### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Natetronn** [multimediamike/xbfuse#4]
Hi Mike, thanks for making xbfuse!

I realize xbfuse is fairly old now but, do you happen to know if anyone ever made a Windows version or something similar by chance?

**Comment by multimediamike** [comment]
No plans, but there should already Windows-native programs that can handle these filesystems.

**Comment by Natetronn** [comment]
Thanks for the quick reply! 

Yeah, I've seen some GUI tools but, I've yet to find something that does what xbfuse does alone and this via the terminal/command line.

I'll keep hunting. 

Thanks again!

**Comment by JayFoxRox** [comment]
Try https://github.com/dokan-dev/dokany/wiki/FUSE
